name: CI/CD pipeline

on:
  push:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: npm ci

      - name: Checking code rules
        run: npm run lint

      - name: Api testing
        run: npm run test:api
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_URI }}
          SECRET: ${{ secrets.SECRET_KEY }}

      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
